[build]
  publish = "app"
  command = "git rev-parse --short HEAD | xargs -I@ sed -i 's|content=\"dev\"|content=\"@\"|' app/index.html"

[[redirects]]
  from = "/dfu-proxy/*"
  to = "/.netlify/functions/dfu-download?path=:splat"
  status = 200
  force = true
